services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: project_dashboard_db
      POSTGRES_USER: project_dashboard_user
      POSTGRES_PASSWORD: project_dashboard_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_dashboard_user -d project_dashboard_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
      - /app/staticfiles
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://project_dashboard_user:project_dashboard_password@db:5432/project_dashboard_db
      SECRET_KEY: django-insecure-!v)z-z-5e2@1bzdtq=!p&=vi4g57ekx5sfj_7162o%6su-_2ti
      ALLOWED_HOSTS: localhost,127.0.0.1
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
